ALTER TABLE "assets"
ADD COLUMN "sha256s" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "telegramMessageIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN "telegramFileIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
